### ISSUE TITLE
BUG: Function 'plot_diary' cannot be employed correctly.

### ISSUE THREAD

**Issue by ZeroCSIS** [scikit-mobility/scikit-mobility#117]
I just ran the official example of 'plot_diary' function in my environment:
( It's in https://github.com/scikit-mobility/scikit-mobility)
```
import skmob
from skmob.preprocessing import detection, clustering
import pandas as pd
 _read the trajectory data (GeoLife, Beijing, China)_
url = 'https://raw.githubusercontent.com/scikit-mobility/scikit-mobility/master/tutorial/data/geolife_sample.txt.gz'
df = pd.read_csv(url, sep=',', compression='gzip')
tdf = skmob.TrajDataFrame(df, latitude='lat', longitude='lon', user_id='user', datetime='datetime')
print(tdf.head())

_detect stops_
stdf = detection.stops(tdf, stop_radius_factor=0.5, minutes_for_a_stop=20.0, spatial_radius_km=0.2, leaving_time=True)
print(stdf.head())

_cluster stops_
cstdf = clustering.cluster(stdf, cluster_radius_km=0.1, min_samples=1)
print(cstdf.head())

_plot the diary of one individual_
user = 1
start_datetime = pd.to_datetime('2008-10-23 030000')
end_datetime = pd.to_datetime('2008-10-30 030000')
ax = cstdf.plot_diary(user, start_datetime=start_datetime, end_datetime=end_datetime)`
```
 However,  some running error came up as follows:

```
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2019.2.4\helpers\pydev\pydevd.py", line 1415, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2019.2.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "G:/Research_in_UTokyo/pythonscript/Trajectory_from_20200622/Traj_0623.py", line 64, in <module>
    cstdf.plot_diary(user, start_datetime=start_datetime, end_datetime=end_datetime,ax = ax)
  File "G:\ProgramData\Anaconda3\lib\site-packages\scikit_mobility-1.0-py3.7.egg\skmob\core\trajectorydataframe.py", line 695, in plot_diary
  File "G:\ProgramData\Anaconda3\lib\site-packages\scikit_mobility-1.0-py3.7.egg\skmob\utils\plot.py", line 309, in plot_diary
  File "g:\programdata\anaconda3\lib\site-packages\matplotlib\axes\_axes.py", line 1053, in axvspan
    p = mpatches.Polygon(verts, **kwargs)
  File "g:\programdata\anaconda3\lib\site-packages\matplotlib\patches.py", line 978, in __init__
    self.set_xy(xy)
  File "g:\programdata\anaconda3\lib\site-packages\matplotlib\patches.py", line 1045, in set_xy
    self._path = Path(xy, closed=self._closed)
  File "g:\programdata\anaconda3\lib\site-packages\matplotlib\path.py", line 127, in __init__
    vertices = _to_unmasked_float_array(vertices)
  File "g:\programdata\anaconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 1390, in _to_unmasked_float_array
    return np.asarray(x, float)
  File "g:\programdata\anaconda3\lib\site-packages\numpy\core\_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: float() argument must be a string or a number, not 'Timestamp'
```
I stepped into the library code, and I find that the bug occurred in line 309 of file 'plot.py':
`                ax.axvspan(t0, t1, lw=0.0, alpha=0.75, color=color, label=cl)
`
It seems that `t0` and `t1` cannot be timestamp type? But the official example shows it should be. 
In addition, my environment is shown as follow, is it caused by incorrect dependent libraries?
```
Package                            Version         
pyproj                             2.4.1
urllib3                            1.24.2
chardet                            3.0.4
MarkupSafe                         1.1.1
matplotlib                         3.1.3
PyQt5                              5.14.1
PyQt5-sip                          12.7.1
PyQtWebEngine                      5.14.0
xlrd                               1.2.0
GDAL                               3.0.2
geojson                            2.5.0
geopandas                          0.7.0+6.ga5e1691
pandas                             1.0.1 
```

**Comment by FilippoSimini** [comment]
I run the code you pasted (changing the path to the data file to `'https://raw.githubusercontent.com/scikit-mobility/scikit-mobility/master/examples/geolife_sample.txt.gz'`) on mybinder (see link in the Readme) and it works fine without any errors. 
The error you get it's most likely a problem with some incorrect dependent library.
