### ISSUE TITLE
H3 tesselation - IndexError: index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by ivandorte** [scikit-mobility/scikit-mobility#174]
Good evening, 
When I run the command `tilers.tiler.get("h3_tessellation", base_shape = gdf)` I receive this error: 
```
epsg:3857
C:\Python38\lib\site-packages\skmob\tessellation\tilers.py:205: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  np.array(list(constants.H3_UTILS['avg_hex_area_km2'].values())) > base_shape.area.values[0])[0][-1]
Traceback (most recent call last):

  File "C:\WS\flickr-geo-search\flickr_geo_elab.py", line 20, in <module>
    h3tess = tilers.tiler.get("h3_tessellation", base_shape = gdf)

  File "C:\Python38\lib\site-packages\skmob\tessellation\tilers.py", line 29, in get
    return self.create(service_id, **kwargs)

  File "C:\Python38\lib\site-packages\skmob\tessellation\tilers.py", line 26, in create
    return tiler(**kwargs)

  File "C:\Python38\lib\site-packages\skmob\tessellation\tilers.py", line 264, in __call__
    return self._build(base_shape, meters, crs)

  File "C:\Python38\lib\site-packages\skmob\tessellation\tilers.py", line 269, in _build
    res = self._get_appropriate_res(base_shape, meters)

  File "C:\Python38\lib\site-packages\skmob\tessellation\tilers.py", line 204, in _get_appropriate_res
    min_res_cover = np.where(

IndexError: index -1 is out of bounds for axis 0 with size 0
```
Strange, because I've reprojected the dataframe from 4326 to 3857, what I'm doing wrong?  However, the command works without reprojection.
This is my code:

```
import pandas as pd
import geopandas as gpd
import skmob
from skmob.tessellation import tilers

df = pd.read_pickle(r"data\Roma_2004_2020_geo.pkl")
gdf = gpd.GeoDataFrame(df, geometry = gpd.points_from_xy(df.longitude, 
                                    df.latitude,
                                    crs = "EPSG:4326").to_crs(epsg=3857))
print(gdf.crs)
h3tess = tilers.tiler.get("h3_tessellation", base_shape = gdf)
h3tess.to_file("h3tess_test.shp")
```

Thanks!!! 
Ivan

**Comment by jonpappalord** [comment]
Since I have no access to file `"data\Roma_2004_2020_geo.pkl"` I tried your code on [this file](https://raw.githubusercontent.com/scikit-mobility/scikit-mobility/master/examples/NY_counties_2011.geojson), which has the following crs: 

```
<Geographic 2D CRS: EPSG:4269>
Name: NAD83
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: North America - onshore and offshore: Canada - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon. Puerto Rico. United States (USA) - Alabama; Alaska; Arizona; Arkansas; California; Colorado; Connecticut; Delaware; Florida; Georgia; Hawaii; Idaho; Illinois; Indiana; Iowa; Kansas; Kentucky; Louisiana; Maine; Maryland; Massachusetts; Michigan; Minnesota; Mississippi; Missouri; Montana; Nebraska; Nevada; New Hampshire; New Jersey; New Mexico; New York; North Carolina; North Dakota; Ohio; Oklahoma; Oregon; Pennsylvania; Rhode Island; South Carolina; South Dakota; Tennessee; Texas; Utah; Vermont; Virginia; Washington; West Virginia; Wisconsin; Wyoming. US Virgin Islands. British Virgin Islands.
- bounds: (167.65071105957, 14.928194130078, -47.743430543984, 86.453745196084)
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich
``` 

The `tilers.get` function works when I run the following code:

```
import pandas as pd
import geopandas as gpd
import skmob
from skmob.tessellation import tilers

url = "https://raw.githubusercontent.com/scikit-mobility/scikit-mobility/master/examples/NY_counties_2011.geojson"
gdf = gpd.read_file(url)

h3tess = tilers.tiler.get("h3_tessellation", meters=500, base_shape=gdf.head(1))
print(h3tess.head())

                                            geometry            H3_INDEX  \
0  POLYGON ((-73.66070 44.62292, -73.66764 44.621...  613255640002854911   
1  POLYGON ((-73.36120 44.81963, -73.36818 44.818...  613255669107130367   
2  POLYGON ((-73.69201 44.72166, -73.69897 44.720...  613255671936188415   
3  POLYGON ((-73.80222 44.48459, -73.80915 44.483...  613255635959545855   
4  POLYGON ((-73.38706 44.65614, -73.39402 44.655...  613255669914533887   

  TILE_ID  
0       0  
1       1  
2       2  
3       3  
4       4 
```

However, the code does not work when I change to projection to 3857: 

```
url = "https://raw.githubusercontent.com/scikit-mobility/scikit-mobility/master/examples/NY_counties_2011.geojson"
gdf = gpd.read_file(url).to_crs(epsg=3857)
h3tess = tilers.tiler.get("h3_tessellation", meters=500, base_shape=gdf.head(1))
print(h3tess.head())

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-3c75ea816716> in <module>
      1 url = "https://raw.githubusercontent.com/scikit-mobility/scikit-mobility/master/examples/NY_counties_2011.geojson"
      2 gdf = gpd.read_file(url).to_crs(epsg=3857)
----> 3 h3tess = tilers.tiler.get("h3_tessellation", meters=500, base_shape=gdf.head(1))
      4 print(h3tess.head())

/opt/anaconda3/envs/skmob122/lib/python3.7/site-packages/skmob/tessellation/tilers.py in get(self, service_id, **kwargs)
     27 
     28     def get(self, service_id, **kwargs):
---> 29         return self.create(service_id, **kwargs)
     30 
     31 

/opt/anaconda3/envs/skmob122/lib/python3.7/site-packages/skmob/tessellation/tilers.py in create(self, key, **kwargs)
     24             raise ValueError(key)
     25 
---> 26         return tiler(**kwargs)
     27 
     28     def get(self, service_id, **kwargs):

/opt/anaconda3/envs/skmob122/lib/python3.7/site-packages/skmob/tessellation/tilers.py in __call__(self, base_shape, meters, which_osm_result, crs, window_size)
    262             cascaded_union(polygons), crs=base_shape.crs)
    263 
--> 264         return self._build(base_shape, meters, crs)
    265 
    266     def _build(self, base_shape, meters, crs=constants.DEFAULT_CRS):

/opt/anaconda3/envs/skmob122/lib/python3.7/site-packages/skmob/tessellation/tilers.py in _build(self, base_shape, meters, crs)
    267 
    268         #  translate input meters to appropriate h3 resolution
--> 269         res = self._get_appropriate_res(base_shape, meters)
    270 
    271         # cover the base_shape with h3 hexagonal polygons

/opt/anaconda3/envs/skmob122/lib/python3.7/site-packages/skmob/tessellation/tilers.py in _get_appropriate_res(self, base_shape, meters)
    203         # find the minimum resolution level which will cover the base_shape
    204         min_res_cover = np.where(
--> 205             np.array(list(constants.H3_UTILS['avg_hex_area_km2'].values())) > base_shape.area.values[0])[0][-1]
    206 
    207         # are the hexagons enough to fill the base_shape?

IndexError: index -1 is out of bounds for axis 0 with size 0
```

Finally, the code works when I change the projection to 4326:

```
url = "https://raw.githubusercontent.com/scikit-mobility/scikit-mobility/master/examples/NY_counties_2011.geojson"
gdf = gpd.read_file(url).to_crs(epsg=4326)
h3tess = tilers.tiler.get("h3_tessellation", meters=500, base_shape=gdf.head(1))
print(h3tess.head())

0  POLYGON ((-73.66070 44.62292, -73.66764 44.621...  613255640002854911   
1  POLYGON ((-73.36120 44.81963, -73.36818 44.818...  613255669107130367   
2  POLYGON ((-73.69201 44.72166, -73.69897 44.720...  613255671936188415   
3  POLYGON ((-73.80222 44.48459, -73.80915 44.483...  613255635959545855   
4  POLYGON ((-73.38706 44.65614, -73.39402 44.655...  613255669914533887   

  TILE_ID  
0       0  
1       1  
2       2  
3       3  
4       4 
```

Therefore, there may be a problem with projection 3857 only. 

Please @miccferr could you check this?

**Comment by jonpappalord** [comment]
Bug fixed. #184 closes the issue.
